---
- name: install go
  hosts: all
  vars:
    go_version: 1.17.5
  become: yes
  roles:
    - fubarhouse.golang
- name: developer setup
  hosts: all
  tasks:
    - name: install software-properties-common
      become: yes
      apt:
        name: software-properties-common
        update_cache: yes
    - name: add PPA
      become: yes
      apt_repository:
        repo: 'ppa:neovim-ppa/unstable'
    - name: install neovim
      become: yes
      apt:
        name: neovim
        update_cache: yes
    - name: sync nvim config
      copy:
        src: ../../nvim
        dest: /home/christian/.config
        owner: christian
        group: christian
        mode: 0644
    - name: install vim plug
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    - name: update vim plugins
      shell: nvim +PlugInstall +qall --headless
    - name: install gopls
      shell: /usr/local/go/bin/go install golang.org/x/tools/gopls@latest

