---
- name: install zsh
  hosts: all
  vars:
    oh_my_zsh_plugins:
      - git
      - fzf
    oh_my_zsh_theme: lukerandall
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: christian
  tags:
    - shell
- name: install go
  hosts: all
  vars:
    go_version: 1.17.8
    go_install_clean: true
  become: yes
  roles:
    - fubarhouse.golang
  tags:
    - go
- name: install docker
  become: yes
  hosts: all
  roles:
    - role: geerlingguy.docker
      docker_users:
        - christian
  tags:
    - docker
- name: developer setup
  hosts: all
  tasks:
    - name: install dev tools
      become: yes
      dnf:
        name:
          - "@Development Tools"
          - "@Development Libraries"
          - libstdc++-static
          - gcc-c++
      tags:
        - build
    - name: enable neovim nightly copr repo
      become: yes
      command:
        cmd: dnf copr enable -y agriffis/neovim-nightly
        creates: "/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:agriffis:neovim-nightly.repo"
    - name: install neovim
      become: yes
      dnf:
        name:
          - neovim
          - python3-neovim
      tags:
        - neovim
    - name: install extras
      become: yes
      package:
        name:
          - ripgrep
          - fzf
          - jq
          - htop
          - tldr
        state: latest
      tags:
        - shell
        - extras
    - name: sync nvim config
      copy:
        src: ../../nvim
        dest: /home/christian/.config
        owner: christian
        group: christian
        mode: 0644
      tags:
        - neovim
    - name: install vim plug
      shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
      tags:
        - neovim
    - name: update vim plugins
      shell: nvim +PlugInstall +qall --headless
      tags:
        - neovim
    - name: install gopls
      shell: /usr/local/go/bin/go install golang.org/x/tools/gopls@latest
      tags:
        - neovim
        - go
    - name: install glow
      shell: /usr/local/go/bin/go install github.com/charmbracelet/glow@v1.4.1
      tags:
        - shell
        - extras
    - name: setup alias for neovim
      lineinfile:
        path: /home/christian/.zshrc
        line: "alias vim='nvim'"
        search_string: "alias vim='nvim'"
        owner: christian
        insertafter: EOF
      tags:
        - shell
    - name: setup go path
      lineinfile:
        path: /home/christian/.zshrc
        line: "export PATH=$PATH:/usr/local/go/bin:/home/christian/go/bin"
        search_string: "export PATH=$PATH:/usr/local/go/bin:/home/christian/go/bin"
        owner: christian
        insertafter: EOF
      tags:
        - shell
    - name: sensu internal env
      lineinfile:
        path: /home/christian/.zshrc
        line: "export SENSU_INTERNAL_ENVIRONMENT=yes"
        search_string: "export SENSU_INTERNAL_ENVIRONMENT=yes"
        owner: christian
        insertafter: EOF
      tags:
        - shell
    - name: gitconfig
      copy:
        src: ../../.gitconfig
        dest: /home/christian
        mode: 0644
      tags:
        - git
    - name: install tmux
      become: yes
      package:
        name: tmux
      tags:
        - tmux
    - name: sync tmux config
      copy:
        src: ../../.tmux.conf
        dest: /home/christian/
        owner: christian
        group: christian
        mode: 0644
      tags:
        - tmux
    - name: sync ssh config
      copy:
        src: ../../.ssh/rc
        dest: /home/christian/.ssh/rc
        owner: christian
        group: christian
        mode: 0644
      tags:
        - tmux
    - name: sync user scripts
      copy:
        src: ../../bin
        dest: /home/christian
        owner: christian
        group: christian
        mode: preserve
      tags:
        - shell
        - extras
    - name: setup user scripts path
      lineinfile:
        path: /home/christian/.zshrc
        line: "export PATH=$PATH:$HOME/bin"
        search_string: "export PATH=$PATH:$HOME/bin"
        owner: christian
        insertafter: EOF
      tags:
        - shell
